---
- name: ensure basic networking tools are installed
  apt: pkg={{ item }} state=present
  with_items:
  - vlan

- include: all_interfaces.yml
  when: network_interfaces

- name: configurations
  template:
    src: device.j2
    dest: "{{ network_interface_path }}/device-{{ item.device }}-{{ item.family | default('inet') }}"
  with_items: "{{network_interfaces}}"
  register: network_configuration_result
  notify:
  - network restart interface service
  - network restart interface command

- include: manage_devices.yml
  when: network_manage_devices

# TODO: use this to restart interfaces that are active
#- name: list active interfaces
#  command: "cat {{ network_interface_states_path }}"
#  changed_when: no
#  when: network_configuration_result.changed
#  register: network_active_interfaces
